window.BUILDLY_DATA = {
  meta:{version:'2.2.0-rc2',mode:'producao',updated:'2026-09-11'},
  works:[
    {id:'obra-futuro',code:'OF-01',name:'Obra do Futuro',city:'',uf:'',active:true}
  ],
  profiles:[
    {id:'owner',label:'Jonacir · Gestor Global',role:'gestor',global:true,specialties:[]},
    {id:'gestor',label:'Gestor da Obra',role:'gestor',global:false,specialties:[]},
    {id:'engenheiro',label:'Engenheiro',role:'engenheiro',global:false,specialties:[]},
    {id:'eng_med',label:'Engenheiro · Medições/Custos',role:'engenheiro',global:false,specialties:['medicoes_custos']},
    {id:'eng_plan',label:'Engenheiro · Planejamento',role:'engenheiro',global:false,specialties:['planejamento']},
    {id:'eng_full',label:'Engenheiro · Medições/Custos + Planejamento',role:'engenheiro',global:false,specialties:['medicoes_custos','planejamento']},
    {id:'tecnico',label:'Técnico',role:'tecnico',global:false,specialties:[]},
    {id:'analista',label:'Analista',role:'analista',global:false,specialties:[]},
    {id:'encarregado',label:'Encarregado',role:'encarregado',global:false,specialties:[]},
    {id:'apontador',label:'Apontador',role:'apontador',global:false,specialties:[]},
    {id:'administrativo',label:'Administrativo',role:'administrativo',global:false,specialties:[]}
  ],
  permissions:{
    gestor:{dashboard:['view'],planejamento:['view','create','edit','delete','approve'],custos:['view','create','edit','delete','approve'],contratos:['view','create','edit','delete','approve'],medicoes:['view','create','edit','delete','approve'],nfs:['view','create','edit','delete','approve'],rdo:['view','create','edit','delete'],cadastro:['view','create','edit','delete'],equipamentos:['view','create','edit','delete'],efetivo:['view','create','edit','delete'],alertas:['view','edit'],ocorrencias:['view','create','edit','delete'],tarefas:['view','create','edit','delete'],reunioes:['view','create','edit','delete'],relatorios:['view','generate'],documentos:['view','create','edit','delete','approve'],orcamento:['view','create','edit','approve'],suprimentos:['view','create','edit','delete','approve'],brain:['view'],auditoria:['view']},
    engenheiro:{dashboard:['view'],planejamento:[],custos:[],contratos:['view'],medicoes:['view','create','edit'],nfs:[],rdo:['view','create','edit','delete'],cadastro:['view','create','edit','delete'],equipamentos:['view','create','edit'],efetivo:['view','create','edit'],alertas:['view'],ocorrencias:['view','create','edit','delete'],tarefas:['view','create','edit'],reunioes:['view','create','edit'],relatorios:['view','generate'],documentos:['view','create','edit'],orcamento:['view'],suprimentos:[],brain:['view'],auditoria:[]},
    tecnico:{dashboard:['view'],planejamento:[],custos:[],contratos:[],medicoes:[],nfs:[],rdo:['view','create','edit'],cadastro:['view','create','edit'],equipamentos:['view'],efetivo:['view'],alertas:['view'],ocorrencias:['view','create','edit'],tarefas:['view','create','edit'],reunioes:[],relatorios:[],documentos:[],orcamento:[],suprimentos:[],brain:['view'],auditoria:[]},
    analista:{dashboard:['view'],planejamento:[],custos:[],contratos:[],medicoes:[],nfs:[],rdo:['view','create','edit'],cadastro:['view','create','edit'],equipamentos:['view'],efetivo:['view'],alertas:['view'],ocorrencias:['view','create','edit'],tarefas:['view','create','edit'],reunioes:[],relatorios:[],documentos:[],orcamento:[],suprimentos:[],brain:['view'],auditoria:[]},
    encarregado:{dashboard:['view'],planejamento:[],custos:[],contratos:[],medicoes:[],nfs:[],rdo:['view','create','edit'],cadastro:['view','create','edit'],equipamentos:['view'],efetivo:['view'],alertas:[],ocorrencias:[],tarefas:[],reunioes:[],relatorios:[],documentos:[],orcamento:[],suprimentos:[],brain:['view'],auditoria:[]},
    apontador:{dashboard:['view'],planejamento:[],custos:[],contratos:[],medicoes:[],nfs:[],rdo:['view','create','edit'],cadastro:['view','create','edit'],equipamentos:['view'],efetivo:['view'],alertas:[],ocorrencias:[],tarefas:[],reunioes:[],relatorios:[],documentos:[],orcamento:[],suprimentos:[],brain:['view'],auditoria:[]},
    administrativo:{dashboard:['view'],planejamento:[],custos:['view','create','edit'],contratos:['view'],medicoes:[],nfs:['view','create','edit'],rdo:['view','create','edit'],cadastro:['view','create','edit'],equipamentos:['view','create','edit'],efetivo:['view','create','edit'],alertas:['view'],ocorrencias:['view','create','edit'],tarefas:['view','create','edit'],reunioes:[],relatorios:[],documentos:[],orcamento:['view'],suprimentos:['view','create','edit'],brain:['view'],auditoria:[]}
  },
  wbs:[],
  cbs:[],
  budgetLines:[],
  budgetAdjustments:[],
  suppliers:[],
  contracts:[],
  contractAmendments:[],
  measurements:[],
  directCosts:[],
  invoices:[],
  payments:[],
  forecastExtras:[],
  purchaseRequests:[],
  purchaseQuotes:[],
  purchaseOrders:[],
  receipts:[],
  auditTrail:[
    {id:'AUD-001',date:'2026-09-11T00:00:00Z',module:'sistema',action:'BASE_ZERADA',reference:'Obra do Futuro',user:'Jonacir',detail:'Base de dados zerada para início da Obra do Futuro.'}
  ],
  planning:[],
  weeklyPlan:[],
  fortnightPlan:[],
  curveS:[],
  restrictions:[],
  rdos:[],
  documents:[],
  documentNotes:[],
  mural:[],
  tasks:[],
  alerts:[],
  occurrences:[],
  meetings:[],
  meetingNotes:[],
  meetingTopics:[],
  equipment:[],
  lightVehicles:[],
  maintenance:[],
  functionsCatalog:[],
  people:[],
  workforce:[],
  activitiesCatalog:[],
  epis:[],
  epiDeliveries:[],
  functionHistory:[],
  equipmentAllocations:[],
  epiFunctionLinks:[]
};
